name: build
# run only when push on main
on: 
  push: 
    branches: [ main ]
jobs:
  build:
    # run on github default vm
    runs-on: ubuntu-latest
    steps:
      # make it available for the runner
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run tests
        run: mvn clean test
